### ISSUE TITLE
device type is mobile in splitscreen for tablets

### ISSUE THREAD

**Issue by jesussmile** [CoderUni/responsive_sizer#43]
Hi!
Thank you for reviving this package. Indeed works great. However,  there are two issue I find

1. When  in tablet and i use splitscreen in ios then the sizer package will register it as a mobile. I believe any width below `600` is considered a mobile ? Perhaps you could consider a `Height` factor too ? this way while in split screen the device is still a tablet ?
2. If i have a row of widget and one of the text value is not with a `const` then the responsive fontsize is weird. gets smaller or bigger for some reason

Any help on this. ?

**Comment by CoderUni** [comment]
Hi, thanks for filing the issue.

1. Yes, you are right. It determines a device is a mobile or not if it's width is less than 600. The height factor is only considered if the orientation is changed. Actually, the device property is more about knowing what kind of layout to display. If the screen is more mobile-like (due to split screen in tablet), we can show them the layout for mobile screens instead. This is actually intended.

2. This is because `const` makes it so that the widget won't rebuild. If the widget doesn't rebuild, it can't update or change itself (font sizes are part of it too). If the device's width and height changes, the `Text`'s font size also updates when you use `dp` or `sp`. Here's the related code for them [here](https://github.com/CoderUni/responsive_sizer/blob/aa35a214716a50e221b7a17d8429fe7431fc5e88/lib/src/extension.dart#L67) . If you don't want the font size to update, you can choose to hard code the font size and remove the added `.sp` or `.dp`.

**Comment by jesussmile** [comment]
Thanks a lot for the tip.
I also realized that iOS treats all its split screens as portrait mode, no matter how the device is oriented. That was causing the issue. After fixing that logic, it's all good now.

**Comment by CoderUni** [comment]
You're welcome. Congrats on fixing it :)
